# Generated by Django 5.2.15 on 2026-06-25 12:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('responsible', 'Пользователь')], default='responsible', max_length=20, verbose_name='роль')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_link_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('telegram_link_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='срок действия Telegram-ссылки')),
                ('telegram_link_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Telegram-ссылка использована')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('applied_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('errors_json', models.JSONField(blank=True, null=True)),
                ('errors_text', models.TextField(blank=True)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('preview_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excel import',
                'verbose_name_plural': 'Excel imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('category', models.CharField(blank=True, max_length=150, verbose_name='категория')),
                ('article', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Артикул должен состоять из 5 цифр.')], verbose_name='артикул')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='штрихкод')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('imported', models.BooleanField(default=False, verbose_name='импортирован')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='архивирован')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_products', to=settings.AUTH_USER_MODEL, verbose_name='архивировал')),
            ],
            options={
                'verbose_name': 'номенклатура',
                'verbose_name_plural': 'номенклатура',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('changed_fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_history', to='core.importbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='core.product')),
            ],
            options={
                'verbose_name': 'Product history',
                'verbose_name_plural': 'Product history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.product')),
            ],
            options={
                'verbose_name': 'остаток',
                'verbose_name_plural': 'остатки',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('reason', models.TextField(blank=True, verbose_name='причина перемещения')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('waiting_sender_approval', 'Ожидает согласия отправителя'), ('sender_rejected', 'Отправитель отказал'), ('waiting_admin_approval', 'Ожидает согласования админа'), ('admin_rejected', 'Админ отклонил'), ('approved', 'Согласовано'), ('shipped', 'Отгружено'), ('in_transit', 'В пути'), ('received', 'Получено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='created', max_length=30, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('sender_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='отправитель согласовал')),
                ('sender_rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='отправитель отказал')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='согласовано')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='отклонено')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='отгружено')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='получено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('sender_rejection_reason', models.TextField(blank=True, verbose_name='причина отказа отправителя')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='причина отказа')),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='последнее напоминание')),
                ('source_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='название склада-отправителя')),
                ('destination_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='название склада-получателя')),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='наименование товара')),
                ('product_category_snapshot', models.CharField(blank=True, max_length=150, verbose_name='категория товара')),
                ('product_article_snapshot', models.CharField(blank=True, max_length=5, verbose_name='артикул товара')),
                ('product_barcode_snapshot', models.CharField(blank=True, max_length=64, verbose_name='штрихкод товара')),
                ('created_by_name_snapshot', models.CharField(blank=True, max_length=300, verbose_name='имя создателя')),
                ('sender_approved_by_name_snapshot', models.CharField(blank=True, max_length=300, verbose_name='имя отправителя, согласовавшего заявку')),
                ('sender_rejected_by_name_snapshot', models.CharField(blank=True, max_length=300, verbose_name='имя отправителя, отказавшего в заявке')),
                ('approved_by_name_snapshot', models.CharField(blank=True, max_length=300, verbose_name='имя согласовавшего')),
                ('rejected_by_name_snapshot', models.CharField(blank=True, max_length=300, verbose_name='имя отклонившего')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='согласовал')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='товар')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_transfers', to=settings.AUTH_USER_MODEL, verbose_name='отклонил')),
                ('sender_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender_approved_transfers', to=settings.AUTH_USER_MODEL, verbose_name='отправитель согласовал')),
                ('sender_rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender_rejected_transfers', to=settings.AUTH_USER_MODEL, verbose_name='отправитель отказал')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='core.warehouse', verbose_name='куда')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='core.warehouse', verbose_name='откуда')),
            ],
            options={
                'verbose_name': 'перемещение',
                'verbose_name_plural': 'перемещения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.PositiveIntegerField()),
                ('change_quantity', models.IntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_history', to='core.importbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.product')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='core.stock')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Stock history',
                'verbose_name_plural': 'Stock history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.warehouse'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('resulting_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='остаток после операции')),
                ('status', models.CharField(blank=True, max_length=30)),
                ('user_name_snapshot', models.CharField(blank=True, max_length=300, verbose_name='пользователь')),
                ('source_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='склад-отправитель')),
                ('destination_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='склад-получатель')),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='наименование товара')),
                ('product_category_snapshot', models.CharField(blank=True, max_length=150, verbose_name='категория товара')),
                ('product_article_snapshot', models.CharField(blank=True, max_length=5, verbose_name='артикул товара')),
                ('product_barcode_snapshot', models.CharField(blank=True, max_length=64, verbose_name='штрихкод товара')),
                ('transfer_reason', models.TextField(blank=True, verbose_name='причина перемещения')),
                ('admin_decision', models.CharField(blank=True, max_length=100, verbose_name='решение администратора')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='причина отказа')),
                ('decision_user_name_snapshot', models.CharField(blank=True, max_length=300, verbose_name='пользователь, принявший решение')),
                ('decision_at', models.DateTimeField(blank=True, null=True, verbose_name='дата решения')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='старое значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='новое значение')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='core.importbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.transfer')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.warehouse')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'операция',
                'verbose_name_plural': 'история операций',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_warehouse_product'),
        ),
    ]
